application:
    name: Voting PoC Default Profile
    version: 0.0.1
jwt:
    authentication:
        secret: jwt_s3cret
        header: votingAuthenticationToken
server:
    address: localhost
    port: 8080
mongodb:
    host: localhost
    port: 27017
    database: voting_poc
    authDatabase: application_users
    user: voting_app
    password: 12345678
---
spring:
    profiles: development
application:
    name: Voting PoC Development
    secret: s3cret
---
spring:
    profiles: developmentNoSecurity
application:
    name: Voting PoC Development - no security
---
spring:
    profiles: production
application:
    secret: 8D~*i%\R|vUGcz334V,;,tQGnLd!Fh
jwt:
    authentication:
        secret: jwt_s3cret
        header: votingAuthenticationToken
# MongoDB Configuration
mongodb:
    server1:
        host: localhost 
        port: 27017
    server2:
        host: localhost
        port: 27018
    server3:
        host: localhost
        port: 27019
    database: voting_poc
    authDatabase: application_users
    user: voting_app
    password: 12345678